srv_ubuntu2004:
  image: ubuntu-20.04-server-cloudimg-amd64.img
ub4:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 4096
  disks:
    - size: 60
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl zsh
  # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
  # - runuser -l ubuntu -c 'bash zsh.sh'
  # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
  # - bash zsh.sh
ub8:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 8192
  disks:
    - size: 120
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl zsh
  # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
  # - runuser -l ubuntu -c 'bash zsh.sh'
  # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
  # - bash zsh.sh
kvm-local_ubuntu2004:
  image: ubuntu-20.04-server-cloudimg-amd64.img
cp:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 4096
  disks:
    - size: 60
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl wget zsh
    # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
    # - runuser -l ubuntu -c 'bash zsh.sh'
    # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
    # - bash zsh.sh
    - curl -Lo kcli-kubeadm.sh https://raw.githubusercontent.com/bashfulrobot/desktoperator/main/kubeadm-test.sh
    - bash ./kcli-kubeadm.sh
wk:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 8192
  disks:
    - size: 120
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl wget zsh
    # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
    # - runuser -l ubuntu -c 'bash zsh.sh'
    # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
    # - bash zsh.sh
    - curl -Lo kcli-kubeadm.sh https://raw.githubusercontent.com/bashfulrobot/desktoperator/main/kubeadm-test.sh
    - bash ./kcli-kubeadm.sh
cp-br:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 4096
  disks:
    - size: 60
  nets:
    - name: br0
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl wget zsh
    # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
    # - runuser -l ubuntu -c 'bash zsh.sh'
    # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
    # - bash zsh.sh
    - curl -Lo kcli-kubeadm.sh https://raw.githubusercontent.com/bashfulrobot/desktoperator/main/kubeadm-test.sh
    - bash ./kcli-kubeadm.sh
wk-br:
  image: ubuntu-20.04-server-cloudimg-amd64.img
  numcpus: 4
  memory: 8192
  disks:
    - size: 120
  nets:
    - name: br0
  cmds:
    - apt update && apt dist-upgrade -y
    - apt install -y git make neovim curl wget zsh
    # - runuser -l ubuntu -c 'curl -Lo zsh.sh https://zsh.bashfulrobot.com'
    # - runuser -l ubuntu -c 'bash zsh.sh'
    # - curl -Lo zsh.sh https://zsh.bashfulrobot.com
    # - bash zsh.sh
    - curl -Lo kcli-kubeadm.sh https://raw.githubusercontent.com/bashfulrobot/desktoperator/main/kubeadm-test.sh
    - bash ./kcli-kubeadm.sh
kvm-local_centos8stream:
  image: CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2
