[colors]
background = '#2C313C'
foreground = '#F5F5F5'
selection-background = '#48B9C7'
selection-foreground = '#F5F5F5'
cursor = '#48B9C7'
black = '#2C313C'
red = '#ED6663'
green = '#4DBA87'
yellow = '#FBC740'
blue = '#48B9C7'
magenta = '#D165E0'
cyan = '#48B9C7'
white = '#F5F5F5'
light_black = '#4F5B66'
light_red = '#ED6663'
light_green = '#4DBA87'
light_yellow = '#FBC740'
light_blue = '#48B9C7'
light_magenta = '#D165E0'
light_cyan = '#48B9C7'
light_white = '#F5F5F5'
